"""Padded multi-instance environment for the single-project RCPSP stack.

Instance catalogs and train/validation splits come exclusively from
``splits.json`` (generated by ``scripts/generate_pool.py``); this module holds no
data-split logic of its own.  Every instance is loaded through the unified
``src.data.adapter.load_core_instance`` (or an injected loader) so the RL stack
shares the exact ``Instance`` representation and serial-SGS decoder with the
rule / GA / GPHH baselines.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from pathlib import Path

import gymnasium as gym
import numpy as np
from gymnasium import spaces

from src.core.rcpsp import Instance
from src.data.adapter import load_core_instance
from src.envs.rcpsp_env import INVALID_ACTION_PENALTY, RCPSPEnv
from src.envs.observation import (
    MAX_SUCCESSORS,
    flatten_observation,
    observation_size,
)


def partition_instance_catalog(
    paths: Sequence[str], parts: int
) -> list[tuple[list[str], list[int]]]:
    """Split a training catalog into per-worker subsets with global indices."""
    if parts < 1:
        raise ValueError("parts must be positive")
    if not paths:
        raise ValueError("paths must not be empty")
    if parts > len(paths):
        raise ValueError("parts cannot exceed the number of paths")
    return [
        (
            [str(paths[index]) for index in range(part, len(paths), parts)],
            list(range(part, len(paths), parts)),
        )
        for part in range(parts)
    ]


class MultiInstanceRCPSPEnv(gym.Env[np.ndarray, int]):
    """Sample one instance per episode with fixed padded observation and action spaces."""

    def __init__(self, instances: list[str | Path],
                 max_activities: int | None = None, max_resources: int | None = None,
                 instance_indices: list[int] | None = None,
                 catalog_size: int | None = None,
                 loader: Callable[[Path], Instance] = load_core_instance):
        super().__init__()
        if not instances:
            raise ValueError("instances must not be empty")
        self.instance_paths = [Path(path) for path in instances]
        self.instances = [loader(path) for path in self.instance_paths]
        self.instance_indices = (
            list(range(len(self.instances))) if instance_indices is None else instance_indices
        )
        self.catalog_size = len(self.instances) if catalog_size is None else catalog_size
        if len(self.instance_indices) != len(self.instances):
            raise ValueError("instance_indices must match instances")
        if any(not 0 <= index < self.catalog_size for index in self.instance_indices):
            raise ValueError("instance_indices must refer to the static graph catalog")
        self.max_activities = max([max_activities or 0] + [len(instance.activities) for instance in self.instances])
        self.max_resources = max([max_resources or 0] + [instance.resource_count for instance in self.instances])
        self.max_successors = MAX_SUCCESSORS
        self.action_space = spaces.Discrete(self.max_activities)
        feature_size = observation_size(self.max_activities, self.max_resources)
        self.observation_space = spaces.Box(0.0, 1.0, (feature_size,), dtype=np.float32)
        # Reuse environment objects across episodes; reset only clears mutable
        # scheduling state and avoids repeated allocation of large buffers.
        self._envs = [RCPSPEnv(instance) for instance in self.instances]
        self._env: RCPSPEnv | None = None
        self._flat_buffers: dict[int, np.ndarray] = {}
        self._capacity_scales = {
            index: np.maximum(np.asarray(instance.capacities, dtype=np.float32), 1.0)
            for index, instance in enumerate(self.instances)
        }

    def reset(self, *, seed=None, options=None):
        super().reset(seed=seed)
        index = int(self.np_random.integers(len(self.instances)))
        self._env = self._envs[index]
        observation, info = self._env.reset(seed=seed)
        self._active_index = index
        return self._encode(observation), {
            **info,
            # Unique instance id (data-root-relative path without extension).
            "instance": self.instances[index].name,
        }

    def step(self, action):
        if self._env is None:
            raise RuntimeError("reset() must be called before step()")
        if not self.action_space.contains(action):
            raise ValueError(f"action must be an integer in [0, {self.max_activities})")
        action = int(action)
        if action >= self.active_env.activity_count:
            observation = self.active_env._observation()
            return (
                self._encode(observation),
                INVALID_ACTION_PENALTY,
                False,
                False,
                {
                    "makespan": self.active_env._state.current_time,
                    "eligible_mask": observation["eligible_mask"].copy(),
                    "invalid_action": True,
                },
            )
        observation, reward, terminated, truncated, info = self._env.step(action)
        return self._encode(observation), reward, terminated, truncated, info

    @property
    def active_env(self) -> RCPSPEnv:
        if self._env is None:
            raise RuntimeError("environment has not been reset")
        return self._env

    def _encode(self, observation):
        env = self.active_env
        buffer = self._flat_buffers.get(self._active_index)
        if buffer is None:
            buffer = np.zeros(
                observation_size(self.max_activities, self.max_resources), dtype=np.float32
            )
            self._flat_buffers[self._active_index] = buffer
        return flatten_observation(
            observation,
            env.instance.capacities,
            env.horizon,
            instance_index=self.instance_indices[self._active_index],
            catalog_size=self.catalog_size,
            max_activities=self.max_activities,
            max_resources=self.max_resources,
            capacity_scale=self._capacity_scales[self._active_index],
            out=buffer,
        )
