#!/usr/bin/env python3
"""GPHH: evolve a priority rule on the RG30 training split and evaluate it.

The training set is read from ``splits.json`` (``train`` split, generated by
``scripts/generate_pool.py``) -- i.e. the protocol's only training pool.  The
evolved rule is decoded by the *same* serial SGS used by ``scripts/baselines.py``
and ``scripts/run_ga.py``, so its makespans are directly comparable.

Two stages:
  1. training  -- ``src.core.gphh.run_gphh`` over the first ``--train-instances``
                 files of the ``train`` split; fitness is the mean relative deviation
                 from the CPM lower bound;
  2. evaluation -- the best rule is applied instance-by-instance to every
                 ``--eval-suites`` set (parallelised with ``--eval-workers``)
                 and written together with the static serial rules for contrast.

Outputs under ``--output-dir``:
  best_rule.txt   -- the evolved rule in infix form
  history.csv     -- best training fitness per generation
  eval_summary.csv-- per-instance makespans (gphh vs serial rules)
  run_meta.json   -- seed, hyper-parameters, training fitness

Example (train on 40 RG30 instances, evaluate on PSPLIB j30, 8 eval workers):
    python -m scripts.run_gphh --data-root data --splits splits.json \
        --train-instances 40 --population 100 --generations 40 \
        --eval-suites psplib_j30 --eval-workers 8 \
        --output-dir outputs/gphh_rcpsp/trial1
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
import sys

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.common import (
    SUITE_SPECS,
    jobs_for_suites,
    map_jobs,
    resolve_suite_ids,
    validate_instance_args,
    write_csv,
)
from src.core.gphh import (
    DEFAULT_CROSSOVER_PROB,
    DEFAULT_ELITE,
    DEFAULT_GENERATIONS,
    DEFAULT_MAX_DEPTH,
    DEFAULT_MUTATION_PROB,
    DEFAULT_POPULATION,
    DEFAULT_TOURNAMENT,
    GPHHParameters,
    rule_makespan,
    rule_to_string,
    run_gphh,
)
from src.core.rules import rule_makespan as static_rule_makespan
from src.data.adapter import load_core_instance

# Static serial rules written next to gphh for contrast (single-pass, same SGS).
CONTRAST_RULES = ("FIFO", "LST", "LFT", "MTS", "GRPW", "SPT")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", type=Path, default=Path("data"))
    parser.add_argument("--splits", type=Path, default=Path("splits.json"))
    parser.add_argument("--train-instances", type=int, default=40)
    parser.add_argument(
        "--eval-suites",
        default=",".join(SUITE_SPECS),
        help="comma-separated suite ids evaluated with the best rule",
    )
    parser.add_argument("--eval-workers", type=int, default=1)
    parser.add_argument("--max-instances", type=int, default=0)
    parser.add_argument("--seed", type=int, default=17)
    parser.add_argument("--population", type=int, default=DEFAULT_POPULATION)
    parser.add_argument("--generations", type=int, default=DEFAULT_GENERATIONS)
    parser.add_argument("--tournament", type=int, default=DEFAULT_TOURNAMENT)
    parser.add_argument("--elite", type=int, default=DEFAULT_ELITE)
    parser.add_argument("--max-depth", type=int, default=DEFAULT_MAX_DEPTH)
    parser.add_argument("--crossover-prob", type=float, default=DEFAULT_CROSSOVER_PROB)
    parser.add_argument("--mutation-prob", type=float, default=DEFAULT_MUTATION_PROB)
    parser.add_argument("--output-dir", type=Path, default=Path("outputs/gphh_rcpsp/default"))
    return parser.parse_args()


def _suite_specs():
    from scripts.common import SUITE_SPECS

    return SUITE_SPECS


def load_training_instances(data_root: Path, splits: Path, count: int):
    """Return the first ``count`` train-split paths as core Instances."""
    if not splits.is_file():
        raise ValueError(f"split manifest not found: {splits}; run scripts/generate_pool.py first")
    manifest = json.loads(splits.read_text())
    paths = manifest["splits"].get("train") or manifest["splits"]["rg30_train"]
    if count < 1 or count > len(paths):
        raise ValueError(f"--train-instances must be in [1, {len(paths)}]")
    return [load_core_instance(data_root / path) for path in paths[:count]]


def evaluate_instance(
    path: Path,
    suite: str,
    rule: object,
    data_root: Path,
) -> dict[str, float | int | str]:
    instance = load_core_instance(path)
    row: dict[str, float | int | str] = {
        "suite": suite,
        "instance": path.name,
        "file": str(path.relative_to(data_root)),
        "n_activities": len(instance.activities),
        "n_resources": instance.resource_count,
        "gphh_makespan": rule_makespan(instance, rule),
    }
    for name in CONTRAST_RULES:
        row[f"serial_{name}"] = static_rule_makespan(instance, name, scheme="serial")
    return row


def write_outputs(
    args: argparse.Namespace,
    best_rule: object,
    best_fitness: float,
    best_generation: int,
    history: tuple[float, ...],
    rows: list[dict[str, float | int | str]],
) -> None:
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "best_rule.txt").write_text(
        f"{rule_to_string(best_rule)}\n# train fitness={best_fitness:.4f} "
        f"(best generation {best_generation})\n"
    )
    with (args.output_dir / "history.csv").open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["generation", "best_train_fitness"])
        writer.writerows(enumerate(history))
    fieldnames = [
        "suite",
        "instance",
        "file",
        "n_activities",
        "n_resources",
        "gphh_makespan",
        *(f"serial_{name}" for name in CONTRAST_RULES),
    ]
    write_csv(rows, args.output_dir / "eval_summary.csv", fieldnames=fieldnames)
    meta = {
        "seed": args.seed,
        "population": args.population,
        "generations": args.generations,
        "tournament": args.tournament,
        "elite": args.elite,
        "max_depth": args.max_depth,
        "crossover_prob": args.crossover_prob,
        "mutation_prob": args.mutation_prob,
        "train_instances": args.train_instances,
        "train_split": manifest["splits"].get("train") and "train" or "rg30_train",
        "best_fitness": best_fitness,
        "best_generation": best_generation,
        "best_rule": rule_to_string(best_rule),
    }
    (args.output_dir / "run_meta.json").write_text(json.dumps(meta, indent=2) + "\n")
    print(f"outputs written to {args.output_dir}")


def print_result(row: dict[str, float | int | str]) -> None:
    print(
        f"{row['suite']}/{row['instance']}: gphh={row['gphh_makespan']} "
        f"serial_LST={row['serial_LST']}",
        flush=True,
    )


def main() -> None:
    args = parse_args()
    validate_instance_args(args.max_instances, args.eval_workers)
    suite_ids = resolve_suite_ids(args.eval_suites)
    params = GPHHParameters(
        population=args.population,
        generations=args.generations,
        tournament=args.tournament,
        elite=args.elite,
        max_depth=args.max_depth,
        crossover_prob=args.crossover_prob,
        mutation_prob=args.mutation_prob,
    )

    print(f"training GPHH on {args.train_instances} training-pool instances (seed {args.seed})")
    training = load_training_instances(args.data_root, args.splits, args.train_instances)
    result = run_gphh(training, seed=args.seed, parameters=params)
    print(
        f"best train fitness={result.best_fitness:.4f} at generation "
        f"{result.best_generation} ({result.evaluations} distinct trees):\n"
        f"  {rule_to_string(result.best_rule)}"
    )

    print("evaluating best rule on eval suites")
    jobs = jobs_for_suites(
        args.data_root, suite_ids, args.max_instances, result.best_rule, args.data_root
    )
    rows = (
        map_jobs(
            evaluate_instance,
            jobs,
            workers=min(args.eval_workers, len(jobs)),
            on_result=print_result,
        )
        if jobs
        else []
    )
    write_outputs(
        args,
        result.best_rule,
        result.best_fitness,
        result.best_generation,
        result.history,
        rows,
    )


if __name__ == "__main__":
    main()
