#!/usr/bin/env python3
"""Train the graph-aware PPO policy on the fixed single-project protocol.

Data comes exclusively from ``splits.json`` (generated by ``scripts/generate_pool.py``):

  * training pool: the ``train`` split (generated PSPLIB-grid pool)
  * in-training validation: the ``validation`` split (per-size 20% cell holdout)
  * final evaluation: any of the ``evaluation`` groups (PSPLIB j30-j120 are the
    held-out benchmark with known BKS; RG300 / Patterson are generalization)

Instances are loaded through ``src.data.parsers`` + ``src.data.adapter`` so the
PPO decoder is the same serial SGS as the rule/GA/GPHH baselines.  The policy
graph is sized to a global activity/resource cap (default auto = the maximum
across every participating split), which lets one model evaluate PSPLIB
j30-j120 (32-122 activities) and RG300 (302 activities) zero-shot.

``--train-max-activities auto`` shrinks only the *training* graph to the
train+validation maximum (32 for the RG30 pool).  Every trainable policy
parameter is size-agnostic, so the policy is widened back to the global cap
before the model is saved and evaluated (``src.training.ppo.widen_policy``);
for a fixed instance the small and widened policies produce identical logits.
This cuts training time by several times without changing the learned function.

Note that the *trained* model is not bit-identical across caps even though the
function is: the action space is ``Discrete(max_activities)`` and
``torch.multinomial`` consumes RNG differently per category count, so stochastic
rollouts diverge after the first action.  Treat a different training cap as a
different random seed, and compare caps with deterministic evaluation.

Evaluation writes ``ppo_eval_summary.csv`` with columns
``suite,file,n_activities,n_resources,ppo_makespan``, consumable by
``scripts/aggregate_results.py --ppo`` for the BKS-gap comparison table.
"""
from __future__ import annotations

import argparse
import csv
from functools import partial
from pathlib import Path
import shutil
import sys
from types import SimpleNamespace

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
import torch
from stable_baselines3 import PPO
from stable_baselines3.common.utils import set_random_seed

from src.core.rcpsp import Instance
from src.envs.multi_instance import partition_instance_catalog
from src.envs.observation import (
    MAX_SUCCESSORS,
    build_static_graph_cache,
    observation_size,
)
from src.training.callbacks import RCPSPMetricsCallback
from src.training.environments import make_multi_env, make_vector_env
from src.data.instances import (
    instance_id,
    loader_for,
    read_protocol,
)
from src.training.ppo import create_ppo, evaluate_paths, widen_policy


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", type=Path, default=Path("data"))
    parser.add_argument(
        "--splits", type=Path, default=Path("splits.json"),
        help="protocol file generated by scripts/generate_pool.py",
    )
    parser.add_argument("--total-timesteps", type=int, default=6_400_000)
    parser.add_argument("--n-envs", type=int, default=16)
    parser.add_argument("--n-steps", type=int, default=256)
    parser.add_argument("--batch-size", type=int, default=4096)
    parser.add_argument("--n-epochs", type=int, default=3)
    parser.add_argument("--gamma", type=float, default=0.999)
    parser.add_argument("--gae-lambda", type=float, default=0.98)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--ent-coef", type=float, default=0.01)
    parser.add_argument("--vf-coef", type=float, default=0.5)
    parser.add_argument(
        "--target-kl", type=float, default=0.0,
        help="stop PPO epochs early above this approximate KL; 0 disables it",
    )
    parser.add_argument("--gin-layers", type=int, default=2)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--device", default="auto")
    parser.add_argument(
        "--mixed-precision", choices=("none", "bf16", "fp16"), default="none",
        help="Autocast GIN and policy heads on CUDA; bf16 is recommended for A800.",
    )
    parser.add_argument(
        "--torch-compile", action="store_true",
        help="Compile the GIN and policy heads (initial iterations include compilation time).",
    )
    parser.add_argument(
        "--compile-mode", choices=("default", "reduce-overhead", "max-autotune"),
        default="reduce-overhead",
    )
    parser.add_argument(
        "--cuda-matmul-precision", choices=("highest", "high", "medium"), default="high",
    )
    parser.add_argument("--vec-env", choices=("auto", "dummy", "subproc"), default="auto")
    parser.add_argument(
        "--start-method", choices=("spawn", "forkserver", "fork"), default="spawn",
    )
    parser.add_argument("--torch-threads", type=int, default=1)
    parser.add_argument("--torch-interop-threads", type=int, default=1)
    parser.add_argument(
        "--max-activities", type=int, default=None,
        help="global activity cap for the policy graph; default = max across all "
             "participating splits (302 when PSPLIB/RG300/Patterson are included)",
    )
    parser.add_argument(
        "--max-resources", type=int, default=None,
        help="global resource cap; default = max across all participating splits",
    )
    parser.add_argument(
        "--train-max-activities", default=None,
        help="activity cap used for the training rollout; 'auto' = max over the "
             "train+validation splits (32 for the RG30 pool). Training on a "
             "smaller padded graph is much cheaper because every trainable policy "
             "parameter is size-agnostic, and the policy is widened to the global "
             "cap before evaluation (see src.training.ppo.widen_policy). Default "
             "None keeps the global cap for training as well.",
    )
    parser.add_argument("--early-stop-patience", type=int, default=0,
                        help="stop after N validation evaluations without improvement; 0 disables it")
    parser.add_argument("--validation-interval", type=int, default=10,
                        help="evaluate the validation split every N rollouts")
    parser.add_argument(
        "--validation-min-delta", type=float, default=0.0,
        help="minimum mean rule-relative-gap improvement required to reset patience",
    )
    parser.add_argument(
        "--ref-rules", type=Path,
        default=Path("outputs/rules_rg30/makespan_summary.csv"),
        help="baselines.py CSV covering rg30 (serial_* columns); reference rule "
             "makespans for validation-based model selection",
    )
    parser.add_argument(
        "--ref-rule", default="serial_LST",
        help="column of --ref-rules used for the validation relative gap",
    )
    parser.add_argument(
        "--eval-suites", default="",
        help="comma-separated evaluation group ids evaluated after training "
             "(from splits.json 'evaluation'); empty skips post-training evaluation",
    )
    parser.add_argument(
        "--eval-all", action="store_true",
        help="evaluate every evaluation group after training (requires a policy "
             "graph large enough for the largest suite, e.g. --max-activities 302)",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=Path("outputs/experiments/ppo/ppo_rcpsp"),
    )
    parser.add_argument(
        "--eval-max-instances", type=int, default=0,
        help="evaluate at most N instances per suite; 0 evaluates all",
    )
    parser.add_argument(
        "--eval-batch-size", type=int, default=32,
        help="number of independent instances advanced per policy inference batch",
    )
    parser.add_argument(
        "--evaluate-only", action="store_true",
        help="Skip training and evaluate output-dir/final_model.zip on every "
             "evaluation group (or the --eval-suites subset).",
    )
    return parser.parse_args()


def resolve_device(requested: str) -> str:
    requested = requested.strip().lower()
    if requested == "auto":
        return "cuda" if torch.cuda.is_available() else "cpu"
    if requested.startswith("cuda") and not torch.cuda.is_available():
        print(f"CUDA {requested!r} unavailable; falling back to CPU")
        return "cpu"
    if requested in {"cpu", "cuda"} or requested.startswith("cuda:"):
        return requested
    raise ValueError("--device must be one of: auto, cpu, cuda, cuda:N")


def configure_torch_runtime(args: argparse.Namespace) -> None:
    torch.set_num_threads(args.torch_threads)
    torch.set_num_interop_threads(args.torch_interop_threads)
    if args.torch_compile and shutil.which("g++") is None:
        print("g++ is unavailable; disabling torch.compile and using eager execution")
        args.torch_compile = False
    if not args.device.startswith("cuda"):
        if args.mixed_precision != "none":
            print("mixed precision requested without CUDA; disabling it")
            args.mixed_precision = "none"
        return
    torch.set_float32_matmul_precision(args.cuda_matmul_precision)
    torch.backends.cuda.matmul.allow_tf32 = args.cuda_matmul_precision != "highest"
    if args.mixed_precision == "bf16" and not torch.cuda.is_bf16_supported():
        raise RuntimeError("the selected CUDA device does not support bf16")


def load_reference_rules(path: Path, column: str) -> dict[str, int]:
    """Map unique instance ids -> reference-rule makespan from a baselines CSV."""
    if not path.is_file():
        raise FileNotFoundError(
            f"--ref-rules not found: {path}; run baselines on rg30 first, e.g.\n"
            "  python -m scripts.baselines --data-root data --suites rg30 "
            "--instance-workers 8 --output-csv outputs/rules_rg30/makespan_summary.csv"
        )
    with path.open(newline="") as fh:
        reader = csv.DictReader(fh)
        if column not in (reader.fieldnames or ()):
            raise ValueError(f"{path} is missing reference column {column!r}")
        refs: dict[str, int] = {}
        for raw in reader:
            key = instance_id(raw["file"])
            try:
                refs[key] = int(float(raw[column]))
            except (TypeError, ValueError) as exc:
                raise ValueError(f"{path}: invalid {column} for {raw.get('file')!r}") from exc
    return refs


def scan_caps(loader, rels: list[str]) -> tuple[int, int]:
    """Resolve global caps over one set of instances (loads are not retained)."""
    max_activities = max_resources = 0
    for rel in rels:
        instance = loader(rel)
        max_activities = max(max_activities, len(instance.activities))
        max_resources = max(max_resources, instance.resource_count)
    return max_activities, max_resources


def evaluate_suites_and_write(
    model: PPO,
    suites: dict[str, list[str]],
    loader,
    name_fn,
    reference_env,
    *,
    seed: int,
    output_dir: Path,
    eval_batch_size: int,
    max_eval_instances: int,
) -> Path:
    """Evaluate the deterministic policy over several suites and write one CSV.

    Columns are aligned with the baseline runners: ``suite``, ``file`` (unique
    data-root-relative path), ``n_activities``, ``n_resources``, ``ppo_makespan``.
    """
    result_path = output_dir / "ppo_eval_summary.csv"
    rows: list[dict] = []
    for suite, rels in suites.items():
        if max_eval_instances:
            rels = rels[:max_eval_instances]
        if not rels:
            continue
        results = dict(evaluate_paths(model, rels, seed, reference_env,
                                      batch_size=eval_batch_size,
                                      loader=loader, name_fn=name_fn))
        for rel in rels:
            instance = loader(rel)
            rows.append({
                "suite": suite,
                "file": rel,
                "n_activities": len(instance.activities),
                "n_resources": instance.resource_count,
                "ppo_makespan": int(results[instance_id(rel)]),
            })
        mean = float(np.mean([int(r["ppo_makespan"]) for r in rows if r["suite"] == suite]))
        print(f"{suite} (n={len(rels)}): mean ppo_makespan={mean:.2f}")
    output_dir.mkdir(parents=True, exist_ok=True)
    with result_path.open("w", newline="") as fh:
        writer = csv.DictWriter(
            fh, fieldnames=["suite", "file", "n_activities", "n_resources", "ppo_makespan"]
        )
        writer.writeheader()
        writer.writerows(rows)
    print(f"ppo evaluation summary: {result_path}")
    return result_path


def validate_rule_relative_gap(
    model: PPO,
    rels: list[str],
    seed: int,
    reference_env,
    reference_rules: dict[str, int],
    loader,
    name_fn,
    *,
    batch_size: int,
    validation_cache,
    restore_cache,
) -> float:
    """Deterministic validation makespans relative to the reference rule."""
    results = evaluate_paths(
        model, rels, seed, reference_env,
        batch_size=batch_size,
        evaluation_cache=validation_cache,
        restore_cache=restore_cache,
        loader=loader, name_fn=name_fn,
    )
    gaps = []
    for instance_name, makespan in results:
        rule_value = reference_rules[instance_name]
        if rule_value <= 0:
            raise ValueError(f"reference rule makespan must be positive for {instance_name}")
        gaps.append((makespan - rule_value) / rule_value)
    gap = float(np.mean(gaps))
    print(f"validation: rule-relative gap={gap:+.6f} over {len(gaps)} instances")
    return gap


def main() -> None:
    args = parse_args()
    if (
        args.total_timesteps < 1
        or args.n_envs < 1
        or args.n_steps < 1
        or args.batch_size < 1
        or args.n_epochs < 1
        or not 0.0 <= args.gamma <= 1.0
        or not 0.0 <= args.gae_lambda <= 1.0
        or args.learning_rate <= 0
        or args.ent_coef < 0
        or args.vf_coef < 0
        or args.target_kl < 0
        or args.gin_layers < 1
        or args.torch_threads < 1
        or args.torch_interop_threads < 1
        or args.early_stop_patience < 0
        or args.validation_interval < 1
        or args.validation_min_delta < 0
    ):
        raise ValueError("invalid hyper-parameters; see argparse help for bounds")
    if args.eval_max_instances < 0 or args.eval_batch_size < 1:
        raise ValueError("--eval-max-instances must be non-negative; --eval-batch-size positive")
    rollout_size = args.n_envs * args.n_steps
    if rollout_size % args.batch_size:
        raise ValueError("batch-size must divide n-envs * n-steps")
    args.device = resolve_device(args.device)
    configure_torch_runtime(args)
    set_random_seed(args.seed)

    protocol = read_protocol(args.splits)
    train_rels = protocol["train"]
    validation_rels = protocol["validation"]
    all_eval_rels = protocol["evaluation"]
    if args.evaluate_only:
        eval_rels = all_eval_rels if not args.eval_suites else {
            s: all_eval_rels[s] for s in args.eval_suites.split(",") if s
        }
    else:
        requested = [s for s in args.eval_suites.split(",") if s] if args.eval_suites else []
        if args.eval_all:
            requested = list(all_eval_rels)
        eval_rels = {s: all_eval_rels[s] for s in requested}

    loader = loader_for(args.data_root)
    participating = list(train_rels) + list(validation_rels)
    for rels in eval_rels.values():
        participating.extend(rels)

    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    model_path = output_dir / "final_model.zip"

    if args.evaluate_only:
        if not model_path.is_file():
            raise FileNotFoundError(f"PPO model not found: {model_path}")
        model = PPO.load(str(model_path), device=args.device)
        extractor = model.policy.features_extractor
        reference_env = SimpleNamespace(
            max_activities=extractor.max_activities,
            max_resources=extractor.max_resources,
        )
        if not eval_rels:
            raise ValueError("--evaluate-only requires --eval-suites or defaults to all")
        evaluate_suites_and_write(
            model, eval_rels, loader, instance_id, reference_env,
            seed=args.seed, output_dir=output_dir,
            eval_batch_size=args.eval_batch_size,
            max_eval_instances=args.eval_max_instances,
        )
        return

    if args.n_envs > len(train_rels):
        raise ValueError(f"--n-envs ({args.n_envs}) exceeds training instances ({len(train_rels)})")

    if args.max_activities is None or args.max_resources is None:
        scanned_activities, scanned_resources = scan_caps(loader, participating)
        max_activities = args.max_activities or scanned_activities
        max_resources = args.max_resources or scanned_resources
        print(f"resolved caps by scan: activities={max_activities} resources={max_resources}")
    else:
        max_activities, max_resources = args.max_activities, args.max_resources
    reference_env = SimpleNamespace(max_activities=max_activities, max_resources=max_resources)

    # Training may run on a smaller padded graph than evaluation. Every trainable
    # parameter of the RCPSP policy is size-agnostic, so the policy is widened to
    # the global cap before the model is saved and evaluated.
    if args.train_max_activities is None:
        train_max_activities, train_max_resources = max_activities, max_resources
    else:
        if args.train_max_activities == "auto":
            scanned_train_activities, scanned_train_resources = scan_caps(
                loader, list(train_rels) + list(validation_rels)
            )
            train_max_activities = min(scanned_train_activities, max_activities)
            train_max_resources = min(scanned_train_resources, max_resources)
        else:
            try:
                train_max_activities = int(args.train_max_activities)
            except ValueError as exc:
                raise ValueError(
                    "--train-max-activities must be a positive integer or 'auto'"
                ) from exc
            train_max_resources = max_resources
        if train_max_activities < 1 or train_max_resources < 1:
            raise ValueError("--train-max-activities must be positive")
        if train_max_activities > max_activities or train_max_resources > max_resources:
            raise ValueError(
                "--train-max-activities cannot exceed the global cap "
                f"({max_activities} activities, {max_resources} resources)"
            )
    widen_policy_graph = (train_max_activities, train_max_resources) != (
        max_activities,
        max_resources,
    )
    train_reference_env = SimpleNamespace(
        max_activities=train_max_activities, max_resources=train_max_resources
    )

    reference_rules = load_reference_rules(args.ref_rules, args.ref_rule)
    missing = [rel for rel in validation_rels if instance_id(rel) not in reference_rules]
    if missing:
        raise ValueError(
            f"--ref-rules does not cover {len(missing)} validation instances; "
            f"first missing: {missing[0]}"
        )

    runtime = (
        f"device={args.device}; envs={args.n_envs}; rollout={rollout_size}; "
        f"batch={args.batch_size}; epochs={args.n_epochs}; lr={args.learning_rate}; "
        f"ent_coef={args.ent_coef}; gamma={args.gamma}; gae_lambda={args.gae_lambda}; "
        f"objective=makespan_only; caps=({max_activities},{max_resources}); "
        f"train_caps=({train_max_activities},{train_max_resources}); "
        f"max_successors={MAX_SUCCESSORS}; "
        f"obs_dim={observation_size(train_max_activities, train_max_resources)}"
    )
    if args.device.startswith("cuda"):
        runtime += f"; gpu={torch.cuda.get_device_name(torch.device(args.device))}"
    print(runtime)

    train_instances = [loader(rel) for rel in train_rels]
    validation_instances = [loader(rel) for rel in validation_rels]
    # Training and in-training validation both run on the training graph; the
    # policy is widened to the global cap only for the final evaluation.
    training_cache = build_static_graph_cache(
        train_instances,
        max_activities=train_max_activities,
        max_resources=train_max_resources,
    )
    validation_cache = build_static_graph_cache(
        validation_instances,
        max_activities=train_max_activities,
        max_resources=train_max_resources,
    )

    worker_catalogs = partition_instance_catalog(train_rels, args.n_envs)
    env_fns = [
        partial(
            make_multi_env,
            worker_paths,
            max_activities=train_max_activities,
            max_resources=train_max_resources,
            instance_indices=worker_indices,
            catalog_size=len(train_rels),
            loader=loader,
        )
        for worker_paths, worker_indices in worker_catalogs
    ]
    env = make_vector_env(env_fns, backend=args.vec_env, start_method=args.start_method)
    try:
        model = create_ppo(
            env,
            instances=train_instances,
            seed=args.seed,
            device=args.device,
            n_steps=args.n_steps,
            batch_size=args.batch_size,
            n_epochs=args.n_epochs,
            gamma=args.gamma,
            gae_lambda=args.gae_lambda,
            learning_rate=args.learning_rate,
            ent_coef=args.ent_coef,
            vf_coef=args.vf_coef,
            target_kl=args.target_kl or None,
            gin_layers=args.gin_layers,
            mixed_precision=args.mixed_precision,
            torch_compile=args.torch_compile,
            compile_mode=args.compile_mode,
            tensorboard_log=str(output_dir / "tensorboard"),
            static_cache=training_cache,
        )
        validation_evaluator = partial(
            validate_rule_relative_gap,
            rels=validation_rels,
            seed=args.seed,
            reference_env=train_reference_env,
            reference_rules=reference_rules,
            loader=loader,
            name_fn=instance_id,
            batch_size=args.eval_batch_size,
            validation_cache=validation_cache,
            restore_cache=training_cache,
        )
        callback = RCPSPMetricsCallback(
            checkpoint_dir=output_dir / "checkpoints",
            early_stop_patience=args.early_stop_patience,
            validation_interval=args.validation_interval,
            validation_min_delta=args.validation_min_delta,
            validation_evaluator=validation_evaluator,
        )
        model.learn(total_timesteps=args.total_timesteps, callback=callback, progress_bar=False)
        best_model_path = callback.best_model_path
        if best_model_path is None or not best_model_path.is_file():
            raise RuntimeError("validation did not produce a best-model checkpoint")
        model.set_parameters(best_model_path, exact_match=True, device=args.device)
        print(f"restored best validation model: {best_model_path}; "
              f"rule-relative gap={callback.best_validation_gap:+.6f}")
        if widen_policy_graph:
            print(
                f"widening policy graph: ({train_max_activities},{train_max_resources}) "
                f"-> ({max_activities},{max_resources}); trainable weights are "
                "size-agnostic, only the static graph cache is rebuilt"
            )
            # Only the weights matter here. The graph cache attached to the
            # widened model is a seed: every evaluation entry point replaces it
            # via ``extractor.set_static_cache`` for the split it is about to
            # run, so the (much smaller) validation catalog is enough and
            # avoids materialising the global-cap cache for the whole training
            # pool a second time.
            model = widen_policy(
                model,
                instances=validation_instances,
                max_activities=max_activities,
                max_resources=max_resources,
                static_cache=build_static_graph_cache(
                    validation_instances,
                    max_activities=max_activities,
                    max_resources=max_resources,
                ),
                device=args.device,
            )
            print(
                f"widened model graph: activities={model.policy.features_extractor.max_activities} "
                f"resources={model.policy.features_extractor.max_resources}"
            )
        model.save(str(output_dir / "final_model"))
        if eval_rels:
            evaluate_suites_and_write(
                model, eval_rels, loader, instance_id, reference_env,
                seed=args.seed, output_dir=output_dir,
                eval_batch_size=args.eval_batch_size,
                max_eval_instances=args.eval_max_instances,
            )
    finally:
        env.close()


if __name__ == "__main__":
    main()
