#!/usr/bin/env python3
"""Train the graph-aware PPO policy on the fixed single-project protocol.

Data comes exclusively from ``splits.json`` (generated by ``scripts/generate_pool.py``):

  * training pool: the ``train`` split (generated PSPLIB-grid pool)
  * in-training validation: the ``validation`` split (32 stratified cells per size)
  * final evaluation: the held-out PSPLIB j30-j120 groups with known BKS

Instances are loaded through ``src.data.parsers`` + ``src.data.adapter`` so the
PPO decoder is the same serial SGS as the rule/GA/GPHH baselines.  The policy
graph uses one activity/resource cap across training, validation and test. The
main protocol has 30-120 real activities plus dummy source/sink nodes, so its
activity cap is 122.

Evaluation writes ``ppo_eval_summary.csv`` with PPO, serial-LST, BKS, and
per-instance BKS-gap columns, consumable by
``scripts/aggregate_results.py --ppo`` for the BKS-gap comparison table.
"""
from __future__ import annotations

import argparse
import csv
import json
from functools import partial
from pathlib import Path
import shutil
import sys
from types import SimpleNamespace

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
import torch
from stable_baselines3 import PPO
from stable_baselines3.common.utils import set_random_seed

from src.envs.multi_instance import partition_instance_catalog
from src.envs.observation import (
    MAX_SUCCESSORS,
    build_static_graph_cache,
    observation_size,
)
from src.training.callbacks import RCPSPMetricsCallback
from src.training.environments import make_multi_env, make_vector_env
from src.data.instances import (
    instance_id,
    loader_for,
    read_protocol,
)
from src.training.ppo import create_ppo, evaluate_paths


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", type=Path, default=Path("data"))
    parser.add_argument(
        "--splits", type=Path, default=Path("splits.json"),
        help="protocol file generated by scripts/generate_pool.py",
    )
    parser.add_argument("--total-timesteps", type=int, default=6_400_000)
    parser.add_argument("--n-envs", type=int, default=16)
    parser.add_argument("--n-steps", type=int, default=256)
    # Update cost scales with n_epochs * rollout, not with the minibatch count,
    # so a smaller minibatch buys optimiser steps at (nearly) constant cost.
    # 16 * 256 = 4096 used to equal batch_size exactly: one minibatch, hence
    # 3 gradient steps per rollout.  1024 gives 4 minibatches / 12 steps on the
    # same rollout and the same wall clock.
    parser.add_argument("--batch-size", type=int, default=1024)
    parser.add_argument("--n-epochs", type=int, default=3)
    # gamma=1 keeps the episode return exactly equal to the makespan objective.
    # With gamma<1 the return is sum_k gamma^k * dT_k / scale, so the terminal
    # increment is weighted by gamma^(n-1), which drifts with the number of
    # activities (0.97 on j30 vs 0.89 on j120 and 0.74 on RG300): a mixed-size
    # training pool then fits a *family* of different objectives.  Episodes are
    # finite, transitions are deterministic and GAE is reset per rollout, so
    # gamma=1 is safe here and is what makes the critical-path shaping term
    # (coef * (makespan - CP) telescoping) strictly potential-based.
    parser.add_argument("--gamma", type=float, default=1.0)
    parser.add_argument("--gae-lambda", type=float, default=0.98)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--ent-coef", type=float, default=0.005)
    parser.add_argument("--vf-coef", type=float, default=0.5)
    parser.add_argument(
        "--critical-path-shaping", type=float, default=0.5,
        help="coefficient for potential-based critical-path reward shaping; 0 disables it",
    )
    parser.add_argument(
        "--target-kl", type=float, default=0.02,
        help="stop PPO epochs early above this approximate KL; 0 disables it",
    )
    parser.add_argument("--gin-layers", type=int, default=2)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--device", default="auto")
    parser.add_argument(
        "--mixed-precision", choices=("none", "bf16", "fp16"), default="none",
        help="Autocast GIN and policy heads on CUDA; bf16 is recommended for A800.",
    )
    parser.add_argument(
        "--torch-compile", action="store_true",
        help="Compile the GIN and policy heads (initial iterations include compilation time).",
    )
    parser.add_argument(
        "--compile-mode", choices=("default", "reduce-overhead", "max-autotune"),
        default="reduce-overhead",
    )
    parser.add_argument(
        "--cuda-matmul-precision", choices=("highest", "high", "medium"), default="high",
    )
    parser.add_argument("--vec-env", choices=("auto", "dummy", "subproc"), default="auto")
    parser.add_argument(
        "--start-method", choices=("spawn", "forkserver", "fork"), default="spawn",
    )
    parser.add_argument("--torch-threads", type=int, default=1)
    parser.add_argument("--torch-interop-threads", type=int, default=1)
    parser.add_argument(
        "--max-activities", type=int, default=None,
        help="global activity cap for the policy graph; default = max across all "
             "participating splits (122 for the main protocol)",
    )
    parser.add_argument(
        "--max-resources", type=int, default=None,
        help="global resource cap; default = max across all participating splits",
    )
    parser.add_argument("--early-stop-patience", type=int, default=12,
                        help="stop after N validation evaluations without improvement; 0 disables it")
    parser.add_argument("--validation-interval", type=int, default=10,
                        help="evaluate the validation split every N rollouts")
    parser.add_argument(
        "--validation-min-delta", type=float, default=0.0,
        help="minimum mean rule-relative-gap improvement required to reset patience",
    )
    parser.add_argument(
        "--ref-rules", type=Path,
        default=Path("outputs/rules_psp_grid/makespan_summary.csv"),
        help="baselines.py CSV covering the training pool (serial_* columns); "
             "reference rule makespans for validation-based model selection",
    )
    parser.add_argument(
        "--ref-rule", default="serial_LST",
        help="column of --ref-rules used for the validation relative gap",
    )
    parser.add_argument(
        "--eval-ref-rules", type=Path,
        default=Path("outputs/rules_psplib/makespan_summary.csv"),
        help="baselines.py CSV for evaluation suites; used for serial_LST "
             "comparison and BKS gaps",
    )
    parser.add_argument(
        "--bks", type=Path, default=Path("data/bks/bks_psplib.json"),
        help="JSON mapping PSPLIB filenames to best-known solutions",
    )
    parser.add_argument(
        "--eval-suites", default="",
        help="comma-separated evaluation group ids evaluated after training "
             "(from splits.json 'evaluation'); empty skips post-training evaluation",
    )
    parser.add_argument(
        "--eval-all", action="store_true",
        help="evaluate every PSPLIB evaluation group after training",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=Path("outputs/experiments/ppo/ppo_rcpsp"),
    )
    parser.add_argument(
        "--eval-max-instances", type=int, default=0,
        help="evaluate at most N instances per suite; 0 evaluates all",
    )
    parser.add_argument(
        "--eval-batch-size", type=int, default=32,
        help="number of independent instances advanced per policy inference batch",
    )
    parser.add_argument(
        "--evaluate-only", action="store_true",
        help="Skip training and evaluate the selected checkpoint on every "
             "evaluation group (or the --eval-suites subset). By default, "
             "use output-dir/checkpoints/best_model.zip.",
    )
    parser.add_argument(
        "--model-path", type=Path, default=None,
        help="checkpoint to load with --evaluate-only; relative paths are "
             "resolved against --output-dir",
    )
    return parser.parse_args()


def resolve_device(requested: str) -> str:
    requested = requested.strip().lower()
    if requested == "auto":
        return "cuda" if torch.cuda.is_available() else "cpu"
    if requested.startswith("cuda") and not torch.cuda.is_available():
        print(f"CUDA {requested!r} unavailable; falling back to CPU")
        return "cpu"
    if requested in {"cpu", "cuda"} or requested.startswith("cuda:"):
        return requested
    raise ValueError("--device must be one of: auto, cpu, cuda, cuda:N")


def configure_torch_runtime(args: argparse.Namespace) -> None:
    torch.set_num_threads(args.torch_threads)
    torch.set_num_interop_threads(args.torch_interop_threads)
    if args.torch_compile:
        args.torch_compile = _torch_compile_available(args)
    if not args.device.startswith("cuda"):
        if args.mixed_precision != "none":
            print("mixed precision requested without CUDA; disabling it")
            args.mixed_precision = "none"
        return
    torch.set_float32_matmul_precision(args.cuda_matmul_precision)
    torch.backends.cuda.matmul.allow_tf32 = args.cuda_matmul_precision != "highest"
    if args.mixed_precision == "bf16" and not torch.cuda.is_bf16_supported():
        raise RuntimeError("the selected CUDA device does not support bf16")


def _torch_compile_available(args: argparse.Namespace) -> bool:
    """Verify torch.compile really works on this host before the run starts.

    ``shutil.which("g++")`` is necessary but not sufficient: inductor also needs
    the rest of the C++ toolchain, and images that ship g++ without ``omp.h``
    raise ``BackendCompilerFailed``.  That used to abort training *after* it had
    already started, so compile a throwaway function first -- with
    ``suppress_errors`` OFF, otherwise dynamo silently falls back to eager and
    the probe would report success on a host whose backend cannot build
    anything.  Once the probe passes, ``suppress_errors`` is switched on as a
    second net for the real graphs.
    """
    if shutil.which("g++") is None:
        print("g++ is unavailable; disabling torch.compile and using eager execution")
        return False
    dynamo_config = getattr(torch, "_dynamo", None)
    if dynamo_config is not None:
        dynamo_config.config.suppress_errors = False
    try:
        probe = torch.compile(
            lambda tensor: tensor.sin().cos(), mode=args.compile_mode, dynamic=True
        )
        probe(torch.zeros(8, device=torch.device(args.device)))
    except Exception as exc:  # noqa: BLE001 - any backend failure must degrade
        print(
            f"torch.compile probe failed ({type(exc).__name__}); disabling "
            "torch.compile and using eager execution "
            "(fix: install OpenMP / set OMP_PREFIX, or keep TORCH_COMPILE=0)"
        )
        return False
    if dynamo_config is not None:
        dynamo_config.config.suppress_errors = True
    print(f"torch.compile verified: mode={args.compile_mode}")
    return True


def load_reference_rules(path: Path, column: str) -> dict[str, int]:
    """Map unique instance ids -> reference-rule makespan from a baselines CSV."""
    if not path.is_file():
        raise FileNotFoundError(
            f"--ref-rules not found: {path}; build it from the training pool "
            "first, e.g.\n"
            "  python -m scripts.baselines --data-root data --instance-workers 8 "
            "--output-csv outputs/rules_psp_grid/makespan_summary.csv"
        )
    with path.open(newline="") as fh:
        reader = csv.DictReader(fh)
        if column not in (reader.fieldnames or ()):
            raise ValueError(f"{path} is missing reference column {column!r}")
        refs: dict[str, int] = {}
        for raw in reader:
            key = instance_id(raw["file"])
            try:
                refs[key] = int(float(raw[column]))
            except (TypeError, ValueError) as exc:
                raise ValueError(f"{path}: invalid {column} for {raw.get('file')!r}") from exc
    return refs


def load_bks(path: Path) -> dict[str, int]:
    """Load BKS values keyed by lower-case PSPLIB filename."""
    if not path.is_file():
        raise FileNotFoundError(f"--bks not found: {path}")
    payload = json.loads(path.read_text(encoding="utf-8"))
    try:
        raw_instances = payload["instances"]
    except (KeyError, TypeError) as exc:
        raise ValueError(f"{path} must contain an 'instances' mapping") from exc
    if not isinstance(raw_instances, dict):
        raise ValueError(f"{path} field 'instances' must be an object")
    bks: dict[str, int] = {}
    for raw_name, raw_value in raw_instances.items():
        try:
            value = int(float(raw_value))
        except (TypeError, ValueError) as exc:
            raise ValueError(f"{path}: invalid BKS for {raw_name!r}") from exc
        if value <= 0:
            raise ValueError(f"{path}: BKS must be positive for {raw_name!r}")
        bks[Path(raw_name).name.lower()] = value
    return bks


def scan_caps(loader, rels: list[str]) -> tuple[int, int, int]:
    """Resolve global caps over one set of instances (loads are not retained)."""
    max_activities = max_resources = max_horizon = 0
    for rel in rels:
        instance = loader(rel)
        max_activities = max(max_activities, len(instance.activities))
        max_resources = max(max_resources, instance.resource_count)
        max_horizon = max(
            max_horizon,
            sum(activity.duration for activity in instance.activities.values()),
        )
    return max_activities, max_resources, max_horizon


def evaluate_suites_and_write(
    model: PPO,
    suites: dict[str, list[str]],
    loader,
    name_fn,
    reference_env,
    *,
    seed: int,
    output_dir: Path,
    eval_batch_size: int,
    max_eval_instances: int,
    evaluation_rules: dict[str, int] | None = None,
    bks: dict[str, int] | None = None,
) -> Path:
    """Evaluate the deterministic policy over several suites and write one CSV.

    Columns are aligned with the baseline runners. When evaluation references
    are supplied, ``serial_LST``, ``bks``, ``gap_serial_LST``, and
    ``gap_ppo_makespan`` are added; gaps are percentages relative to BKS.
    """
    result_path = output_dir / "ppo_eval_summary.csv"
    rows: list[dict] = []
    for suite, rels in suites.items():
        if max_eval_instances:
            rels = rels[:max_eval_instances]
        if not rels:
            continue
        results = dict(evaluate_paths(model, rels, seed, reference_env,
                                      batch_size=eval_batch_size,
                                      loader=loader, name_fn=name_fn))
        for rel in rels:
            instance = loader(rel)
            row = {
                "suite": suite,
                "file": rel,
                "n_activities": len(instance.activities),
                "n_resources": instance.resource_count,
                "ppo_makespan": int(results[instance_id(rel)]),
            }
            if evaluation_rules is not None or bks is not None:
                if evaluation_rules is None or bks is None:
                    raise ValueError(
                        "evaluation_rules and bks must be supplied together"
                    )
                key = instance_id(rel)
                bks_key = Path(rel).name.lower()
                if key not in evaluation_rules:
                    raise ValueError(f"evaluation rules do not cover {rel}")
                if bks_key not in bks:
                    raise ValueError(f"BKS does not cover {rel}")
                lst = evaluation_rules[key]
                best_known = bks[bks_key]
                row.update({
                    "serial_LST": lst,
                    "bks": best_known,
                    "gap_serial_LST": round(
                        100.0 * (lst - best_known) / best_known, 2
                    ),
                    "gap_ppo_makespan": round(
                        100.0 * (row["ppo_makespan"] - best_known) / best_known, 2
                    ),
                })
            rows.append(row)
        mean = float(np.mean([int(r["ppo_makespan"]) for r in rows if r["suite"] == suite]))
        print(f"{suite} (n={len(rels)}): mean ppo_makespan={mean:.2f}")
        if evaluation_rules is not None:
            suite_rows = [r for r in rows if r["suite"] == suite]
            print(
                f"{suite} (n={len(rels)}): mean gap PPO="
                f"{np.mean([r['gap_ppo_makespan'] for r in suite_rows]):+.2f}%; "
                f"serial_LST={np.mean([r['gap_serial_LST'] for r in suite_rows]):+.2f}%"
            )
    output_dir.mkdir(parents=True, exist_ok=True)
    with result_path.open("w", newline="") as fh:
        fieldnames = ["suite", "file", "n_activities", "n_resources", "ppo_makespan"]
        if evaluation_rules is not None:
            fieldnames += [
                "serial_LST", "bks", "gap_serial_LST", "gap_ppo_makespan"
            ]
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"ppo evaluation summary: {result_path}")
    return result_path


def validate_rule_relative_gap(
    model: PPO,
    rels: list[str],
    seed: int,
    reference_env,
    reference_rules: dict[str, int],
    loader,
    name_fn,
    *,
    batch_size: int,
    validation_cache,
    restore_cache,
) -> float:
    """Deterministic validation makespans relative to the reference rule."""
    results = evaluate_paths(
        model, rels, seed, reference_env,
        batch_size=batch_size,
        evaluation_cache=validation_cache,
        restore_cache=restore_cache,
        loader=loader, name_fn=name_fn,
    )
    gaps = []
    for instance_name, makespan in results:
        rule_value = reference_rules[instance_name]
        if rule_value <= 0:
            raise ValueError(f"reference rule makespan must be positive for {instance_name}")
        gaps.append((makespan - rule_value) / rule_value)
    gap = float(np.mean(gaps))
    print(f"validation: rule-relative gap={gap:+.6f} over {len(gaps)} instances")
    return gap


def main() -> None:
    args = parse_args()
    if (
        args.total_timesteps < 1
        or args.n_envs < 1
        or args.n_steps < 1
        or args.batch_size < 1
        or args.n_epochs < 1
        or not 0.0 <= args.gamma <= 1.0
        or not 0.0 <= args.gae_lambda <= 1.0
        or args.learning_rate <= 0
        or args.ent_coef < 0
        or args.vf_coef < 0
        or args.critical_path_shaping < 0
        or args.target_kl < 0
        or args.gin_layers < 1
        or args.torch_threads < 1
        or args.torch_interop_threads < 1
        or args.early_stop_patience < 0
        or args.validation_interval < 1
        or args.validation_min_delta < 0
    ):
        raise ValueError("invalid hyper-parameters; see argparse help for bounds")
    if args.eval_max_instances < 0 or args.eval_batch_size < 1:
        raise ValueError("--eval-max-instances must be non-negative; --eval-batch-size positive")
    rollout_size = args.n_envs * args.n_steps
    if rollout_size % args.batch_size:
        raise ValueError("batch-size must divide n-envs * n-steps")
    args.device = resolve_device(args.device)
    configure_torch_runtime(args)
    set_random_seed(args.seed)

    protocol = read_protocol(args.splits)
    train_rels = protocol["train"]
    validation_rels = protocol["validation"]
    all_eval_rels = protocol["evaluation"]
    if args.evaluate_only:
        eval_rels = all_eval_rels if not args.eval_suites else {
            s: all_eval_rels[s] for s in args.eval_suites.split(",") if s
        }
    else:
        requested = [s for s in args.eval_suites.split(",") if s] if args.eval_suites else []
        if args.eval_all:
            requested = list(all_eval_rels)
        eval_rels = {s: all_eval_rels[s] for s in requested}

    loader = loader_for(args.data_root)
    participating = list(train_rels) + list(validation_rels)
    for rels in eval_rels.values():
        participating.extend(rels)

    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    evaluation_rules = None
    evaluation_bks = None
    if eval_rels:
        evaluation_rules = load_reference_rules(
            args.eval_ref_rules, "serial_LST"
        )
        evaluation_bks = load_bks(args.bks)
        missing_rules = [
            rel
            for rels in eval_rels.values()
            for rel in rels
            if instance_id(rel) not in evaluation_rules
        ]
        missing_bks = [
            rel
            for rels in eval_rels.values()
            for rel in rels
            if Path(rel).name.lower() not in evaluation_bks
        ]
        if missing_rules:
            raise ValueError(
                f"--eval-ref-rules does not cover {len(missing_rules)} evaluation "
                f"instances; first missing: {missing_rules[0]}"
            )
        if missing_bks:
            raise ValueError(
                f"--bks does not cover {len(missing_bks)} evaluation instances; "
                f"first missing: {missing_bks[0]}"
            )

    if args.evaluate_only:
        model_path = args.model_path or Path("checkpoints/best_model.zip")
        if not model_path.is_absolute():
            model_path = output_dir / model_path
        if not model_path.is_file():
            raise FileNotFoundError(f"PPO model not found: {model_path}")
        model = PPO.load(str(model_path), device=args.device)
        extractor = model.policy.features_extractor
        reference_env = SimpleNamespace(
            max_activities=extractor.max_activities,
            max_resources=extractor.max_resources,
            max_horizon=extractor.max_horizon,
        )
        if not eval_rels:
            raise ValueError("--evaluate-only requires --eval-suites or defaults to all")
        evaluate_suites_and_write(
            model, eval_rels, loader, instance_id, reference_env,
            seed=args.seed, output_dir=output_dir,
            eval_batch_size=args.eval_batch_size,
            max_eval_instances=args.eval_max_instances,
            evaluation_rules=evaluation_rules,
            bks=evaluation_bks,
        )
        return

    if args.n_envs > len(train_rels):
        raise ValueError(f"--n-envs ({args.n_envs}) exceeds training instances ({len(train_rels)})")

    if args.max_activities is None or args.max_resources is None:
        scanned_activities, scanned_resources, scanned_horizon = scan_caps(loader, participating)
        max_activities = args.max_activities or scanned_activities
        max_resources = args.max_resources or scanned_resources
        max_horizon = scanned_horizon
        print(
            f"resolved caps by scan: activities={max_activities} "
            f"resources={max_resources} horizon={max_horizon}"
        )
    else:
        max_activities, max_resources = args.max_activities, args.max_resources
        _, _, max_horizon = scan_caps(loader, participating)
    reference_env = SimpleNamespace(
        max_activities=max_activities,
        max_resources=max_resources,
        max_horizon=max_horizon,
    )

    reference_rules = load_reference_rules(args.ref_rules, args.ref_rule)
    missing = [rel for rel in validation_rels if instance_id(rel) not in reference_rules]
    if missing:
        raise ValueError(
            f"--ref-rules does not cover {len(missing)} validation instances; "
            f"first missing: {missing[0]}"
        )

    runtime = (
        f"device={args.device}; envs={args.n_envs}; rollout={rollout_size}; "
        f"batch={args.batch_size}; epochs={args.n_epochs}; lr={args.learning_rate}; "
        f"ent_coef={args.ent_coef}; gamma={args.gamma}; gae_lambda={args.gae_lambda}; "
        f"critical_path_shaping={args.critical_path_shaping}; "
        f"objective=makespan_only; caps=({max_activities},{max_resources}); "
        f"max_successors={MAX_SUCCESSORS}; "
        f"state=exact; max_horizon={max_horizon}; "
        f"obs_dim={observation_size(max_activities, max_resources, max_horizon)}"
    )
    if args.device.startswith("cuda"):
        runtime += f"; gpu={torch.cuda.get_device_name(torch.device(args.device))}"
    print(runtime)

    train_instances = [loader(rel) for rel in train_rels]
    validation_instances = [loader(rel) for rel in validation_rels]
    training_cache = build_static_graph_cache(
        train_instances,
        max_activities=max_activities,
        max_resources=max_resources,
    )
    validation_cache = build_static_graph_cache(
        validation_instances,
        max_activities=max_activities,
        max_resources=max_resources,
    )

    worker_catalogs = partition_instance_catalog(train_rels, args.n_envs)
    env_fns = [
        partial(
            make_multi_env,
            worker_paths,
            max_activities=max_activities,
            max_resources=max_resources,
            max_horizon=max_horizon,
            instance_indices=worker_indices,
            catalog_size=len(train_rels),
            reward_shaping_coef=args.critical_path_shaping,
            loader=loader,
        )
        for worker_paths, worker_indices in worker_catalogs
    ]
    env = make_vector_env(env_fns, backend=args.vec_env, start_method=args.start_method)
    try:
        model = create_ppo(
            env,
            instances=train_instances,
            seed=args.seed,
            device=args.device,
            n_steps=args.n_steps,
            batch_size=args.batch_size,
            n_epochs=args.n_epochs,
            gamma=args.gamma,
            gae_lambda=args.gae_lambda,
            learning_rate=args.learning_rate,
            ent_coef=args.ent_coef,
            vf_coef=args.vf_coef,
            target_kl=args.target_kl or None,
            gin_layers=args.gin_layers,
            mixed_precision=args.mixed_precision,
            torch_compile=args.torch_compile,
            compile_mode=args.compile_mode,
            tensorboard_log=str(output_dir / "tensorboard"),
            static_cache=training_cache,
        )
        validation_evaluator = partial(
            validate_rule_relative_gap,
            rels=validation_rels,
            seed=args.seed,
            reference_env=reference_env,
            reference_rules=reference_rules,
            loader=loader,
            name_fn=instance_id,
            batch_size=args.eval_batch_size,
            validation_cache=validation_cache,
            restore_cache=training_cache,
        )
        callback = RCPSPMetricsCallback(
            checkpoint_dir=output_dir / "checkpoints",
            early_stop_patience=args.early_stop_patience,
            validation_interval=args.validation_interval,
            validation_min_delta=args.validation_min_delta,
            validation_evaluator=validation_evaluator,
            reference_rule_name=args.ref_rule,
        )
        model.learn(total_timesteps=args.total_timesteps, callback=callback, progress_bar=False)
        best_model_path = callback.best_model_path
        if best_model_path is None or not best_model_path.is_file():
            raise RuntimeError("validation did not produce a best-model checkpoint")
        model.set_parameters(best_model_path, exact_match=True, device=args.device)
        print(f"restored best validation model: {best_model_path}; "
              f"rule-relative gap={callback.best_validation_gap:+.6f}")
        model.save(str(output_dir / "final_model"))
        if eval_rels:
            evaluate_suites_and_write(
                model, eval_rels, loader, instance_id, reference_env,
                seed=args.seed, output_dir=output_dir,
                eval_batch_size=args.eval_batch_size,
                max_eval_instances=args.eval_max_instances,
                evaluation_rules=evaluation_rules,
                bks=evaluation_bks,
            )
    finally:
        env.close()


if __name__ == "__main__":
    main()
